services:
  pytorch-rocm:
    build: .
    container_name: pytorch-rocm 
    tty: true             # Аналог флага -t 
    stdin_open: true      # Аналог флага -i 
    network_mode: "host"  # Контейнер использует сеть хоста
    shm_size: '16gb'

    # Настройка видеокарты AMD
    devices:
      - "/dev/kfd:/dev/kfd"    
      - "/dev/dri:/dev/dri"
    group_add:
      - video

    volumes: # <папка_на_хосте>:<папка_в_контейнере>
      - .:/workspace
      - ~/.kaggle_cache:/root/.kaggle  # Сохраняем временные файлы загрузки
    working_dir: /workspace

    # Авторизация в Kaggle через env переменные
    environment:
      - KAGGLE_USERNAME=romanlednev
      - KAGGLE_KEY=1c9d02c48008cd5730ff1c38c3ca1e2d
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
